name: CI Pipeline - Flask Docker App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Run tests (if you have test cases)
    - name: Run tests
      run: |
        echo "Running tests..."
        pytest || echo "No tests found"

    # Step 5: Build Docker image
    - name: Build Docker image
      run: docker build -t my-flask-app:latest .

    # Step 6: (Optional) Push image to DockerHub
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push image to DockerHub
      run: |
        docker tag my-flask-app:latest ${{ secrets.DOCKER_USERNAME }}/my-flask-app:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/my-flask-app:latest
